# Generated by Django 5.0.7 on 2024-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, upload_to='infos_photo', verbose_name='이미지'),
        ),
    ]
