# Generated by Django 4.2.13 on 2024-08-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='accounts_photo/default_profile.png', null=True, upload_to='accounts_photo', verbose_name='프로필'),
        ),
    ]
