# Generated by Django 5.0.7 on 2024-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='accounts_photo/accounts_default.jpg', null=True, upload_to='accounts_photo', verbose_name='프로필'),
        ),
    ]
