# Generated by Django 5.0.7 on 2024-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='accounts_photo', verbose_name='프로필'),
        ),
    ]
