# Generated by Django 5.0.7 on 2024-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'max_length': '닉네임은 8자 이내로 설정해주세요.', 'unique': '이미 사용중인 닉네임입니다..'}, max_length=8, unique=True, verbose_name='닉네임'),
        ),
    ]
