# Generated by Django 5.0.7 on 2024-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='pageUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='period',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
