# Generated by Django 5.0.7 on 2024-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_alter_datamodel_description_alter_datamodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='audience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='period',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
