# Generated by Django 4.2.13 on 2024-08-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_alter_datamodel_image_alter_datamodel_pageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
