# Generated by Django 5.0.7 on 2024-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
