# Generated by Django 5.0.7 on 2024-07-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0007_comment_profile_comment_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
