# Generated by Django 5.0.7 on 2024-07-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamodel',
            options={'ordering': ['-period']},
        ),
    ]
