# Generated by Django 5.0.7 on 2024-07-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0009_alter_datamodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ['-created_at']},
        ),
    ]
