# Generated by Django 5.0.7 on 2024-07-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0010_alter_scrap_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='is_scrapped',
            field=models.BooleanField(default=False),
        ),
    ]
