# Generated by Django 5.0.7 on 2024-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0011_scrap_is_scrapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
