# Generated by Django 5.0.7 on 2024-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0012_comment_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='image',
            field=models.URLField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='scrap',
            name='period',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='scrap',
            name='place',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='scrap',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
