# Generated by Django 5.0.7 on 2024-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0015_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='댓글'),
        ),
    ]
