# Generated by Django 5.0.7 on 2024-07-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0016_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='댓글'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='image',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='period',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='place',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
