# Generated by Django 5.0.7 on 2024-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0017_alter_comment_comment_alter_scrap_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='pageUrl',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
