# Generated by Django 5.0.7 on 2024-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='books_photo/book_default.jpg', upload_to='books_photo', verbose_name='이미지'),
        ),
    ]
