# Generated by Django 5.0.7 on 2024-07-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_created_at2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nickname',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
