# Generated by Django 5.0.7 on 2024-07-27 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_nickname'),
        ('datas', '0013_scrap_image_scrap_period_scrap_place_scrap_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datas.datamodel'),
            preserve_default=False,
        ),
    ]
