# Generated by Django 5.0.7 on 2024-07-25 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='제목')),
                ('author', models.CharField(max_length=15, verbose_name='아티스트')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='musics_photo', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('username', models.CharField(blank=True, editable=False, max_length=150)),
                ('profile', models.URLField(blank=True, editable=False)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
