# Generated by Django 4.2.13 on 2024-08-02 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('author', models.CharField(max_length=50, verbose_name='아티스트')),
                ('content', models.TextField(max_length=300, verbose_name='내용')),
                ('image', models.ImageField(blank=True, default='musics_photo/music_default.png', upload_to='musics_photo', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('username', models.CharField(blank=True, editable=False, max_length=150)),
                ('profile', models.URLField(blank=True, editable=False)),
                ('created_at2', models.DateTimeField(auto_now_add=True, verbose_name='작성일2')),
                ('nickname', models.CharField(blank=True, editable=False, max_length=150)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.datamodel')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
