# Generated by Django 5.0.7 on 2024-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_music_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, default='musics_photo/music_default.png', upload_to='musics_photo', verbose_name='이미지'),
        ),
    ]
