# Generated by Django 5.0.7 on 2024-07-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_alter_music_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at']},
        ),
    ]
