# Generated by Django 5.0.7 on 2024-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_music_created_at2'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='nickname',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
