# Generated by Django 5.0.7 on 2024-07-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0013_scrap_image_scrap_period_scrap_place_scrap_title'),
        ('musics', '0006_music_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datas.datamodel'),
            preserve_default=False,
        ),
    ]
