# Generated by Django 5.0.7 on 2024-07-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_alter_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.CharField(max_length=50, verbose_name='아티스트'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
