# Generated by Django 5.0.7 on 2024-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_alter_music_author_alter_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='content',
            field=models.TextField(max_length=300, verbose_name='내용'),
        ),
    ]
