# Generated by Django 4.2.13 on 2024-08-02 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='제목')),
                ('content', models.TextField(max_length=300, verbose_name='내용')),
                ('img', models.ImageField(blank=True, default='posts_photo/post_default.png', upload_to='posts_photo', verbose_name='사진')),
                ('view_at', models.DateTimeField(blank=True, null=True, verbose_name='관람일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('username', models.CharField(blank=True, editable=False, max_length=150)),
                ('profile', models.URLField(blank=True, editable=False)),
                ('nickname', models.CharField(blank=True, editable=False, max_length=150)),
                ('created_at2', models.DateTimeField(auto_now_add=True, verbose_name='작성일2')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField(verbose_name='분석 결과')),
                ('happiness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='행복 퍼센트')),
                ('sadness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='슬픔 퍼센트')),
                ('anger', models.FloatField(blank=True, default=0.0, null=True, verbose_name='분노 퍼센트')),
                ('anxiety', models.FloatField(blank=True, default=0.0, null=True, verbose_name='불안 퍼센트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
