# Generated by Django 5.0.7 on 2024-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
