# Generated by Django 5.0.7 on 2024-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_profile_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='post_default.png', upload_to='posts_photo', verbose_name='사진'),
        ),
    ]
