# Generated by Django 5.0.7 on 2024-07-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='posts_photo/post_default.png', upload_to='posts_photo', verbose_name='사진'),
        ),
    ]
