# Generated by Django 5.0.7 on 2024-07-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_like_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
