# Generated by Django 5.0.7 on 2024-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='관람일'),
        ),
    ]
